[package]
name = "gt"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.17", features = ["derive"] }
env_logger = "0.10.1"
log = "0.4.20"
anyhow = "1.0.79"
bytes = "1.5.0"
http-body-util = "0.1.0"
hyper = { version = "1.1.0", features = ["http1", "client"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["process"] }
url = "2.5.0"
webrtc = "0.9.0"
serde_yaml = "0.9.30"
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }
